services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finance_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    networks:
      - finance_network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finance_worker
    restart: unless-stopped
    command: php artisan queue:work rabbitmq --queue=notifications,default --sleep=3 --tries=3 --timeout=60
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
      - rabbitmq
    networks:
      - finance_network

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finance_scheduler
    restart: unless-stopped
    command: php artisan schedule:work
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
      - rabbitmq
    networks:
      - finance_network

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: finance_rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - finance_network

  mailpit:
    image: axllent/mailpit
    container_name: finance_mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - finance_network

  db:
    image: postgres:15
    container_name: finance_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - finance_network

  prometheus:
    image: prom/prometheus
    container_name: finance_prometheus
    restart: unless-stopped
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - finance_network

  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana
    container_name: finance_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./docker/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - grafana_data:/var/lib/grafana
    networks:
      - finance_network

networks:
  finance_network:
    driver: bridge

volumes:
  pgdata:
  grafana_data:
