services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finance_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - finance_network

  db:
    image: postgres:15
    container_name: finance_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - finance_network

  prometheus:
    image: prom/prometheus
    container_name: finance_prometheus
    restart: unless-stopped
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - finance_network

  grafana:
    image: grafana/grafana
    container_name: finance_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - finance_network

networks:
  finance_network:
    driver: bridge

volumes:
  pgdata:
